import { GetStaticProps } from "next";
import Head from "next/head";
import { DataProps, Trending } from "../typing";
import Header from "../components/header/Header";
import TrendingComp from "../components/body/TrendingComp";

export default function Home({ trending }: DataProps) {
  return (
    <>
      <Head>
        <title>NetFlix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <TrendingComp results={trending.results} />
    </>
  );
}
export const getStaticProps: GetStaticProps = async (content) => {
  const trending = await getTrendingMovies();
  return {
    props: { trending }, // will be passed to the page component as props
  };
};

const getTrendingMovies = async () => {
  const res = await fetch("http://localhost:3000/api/trending");
  const { data } = await res.json();
  return data;
};
